name: Good Stuff?

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Ngrok
        run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
      - name: Setup Ngrok
        run: |
          Expand-Archive ngrok.zip
          .\ngrok\ngrok.exe config add-authtoken 7mqSr9y7bGPBDqt614Ytb_3d4svuCrb5cvxtcJSq6zx
      - name: Setup RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
      - name: Start Ngrok
        run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
      - name: Start
        run: cmd /c start.bat
      - name: Looper
        run: cmd /c looper.bat
